### ISSUE TITLE
I can't enter hex codes on Sutemo's Character Creator

### ISSUE THREAD

**Issue by StarProgramer** [ShatReal/sutemo#2]
Hi, I was using Sutemo's Character Creator to make some characters, but I wanted to use a certain color. However, when I clicked the "HEX #" area, it wouldn't let me enter anything. I tried both typing and copying and pasting, but it just refuses to work. Can you look into it, please? 

Thank you in advance.

**Comment by ShatReal** [comment]
Sorry about that. They should be fixed now!
